'use client'
import CMS from './Cms'

const general = [
  { name: 'Aptos', count: 1293 },
  { name: 'Move', count: 1161 },
  { name: '生态', count: 732 },
  { name: 'XFi', count: 567 },
  { name: '智能合约审计', count: 176 },
  { name: '游戏', count: 356 },
  { name: '去中心化存储', count: 178 },
  { name: '区块链监管与合规', count: 145 },
  { name: '可视化', count: 156 },
  { name: '跨链互操作', count: 289 },
  { name: '代币经济学', count: 245 },
  { name: 'NFT', count: 412 },
  { name: '去中心化身份 (DID)', count: 189 },
  { name: '元宇宙', count: 278 },
  { name: '社交网络', count: 203 },
  { name: '数据隐私', count: 167 },
  { name: '去中心化治理', count: 221 },
  { name: '区块链教育', count: 198 },
  { name: '可持续发展', count: 134 },
  { name: '加密艺术', count: 176 },
  { name: '区块链医疗', count: 152 },
  { name: '供应链', count: 187 },
  { name: '区块链投票', count: 129 },
  { name: '去中心化科学 (DeSci)', count: 108 },
  { name: '区块链旅游', count: 95 },
  { name: '区块链慈善', count: 112 },
  { name: '去中心化工作', count: 143 },
  { name: '加密货币采矿', count: 165 },
  { name: '区块链能源', count: 128 },
  { name: '区块链房地产', count: 137 },
]

const technology = [
  { name: '开发工具', count: 623 },
  { name: '安全性', count: 53 },
  { name: '性能优化', count: 70 },
  { name: '零知识证明', count: 201 },
  { name: '智能合约', count: 854 },
  { name: '共识机制', count: 312 },
  { name: '分片技术', count: 178 },
  { name: '状态通道', count: 145 },
  { name: '侧链', count: 167 },
  { name: 'L2 扩容', count: 289 },
  { name: 'DAG 技术', count: 123 },
  { name: '密码学', count: 234 },
  { name: '区块链虚拟机', count: 198 },
  { name: '去中心化存储协议', count: 176 },
  { name: 'P2P 网络', count: 209 },
  { name: '智能合约形式化验证', count: 132 },
  { name: '区块链数据压缩', count: 108 },
  { name: '跨链协议', count: 245 },
  { name: '区块链索引', count: 156 },
  { name: '轻客户端技术', count: 134 },
  { name: '区块链数据库', count: 187 },
  { name: '链上治理机制', count: 165 },
  { name: '区块链隐私计算', count: 198 },
  { name: '分布式随机数生成', count: 112 },
  { name: '区块链时间戳', count: 98 },
  { name: '区块链身份验证', count: 176 },
  { name: '智能合约语言', count: 223 },
  { name: '区块链网络安全', count: 189 },
  { name: '区块链数据分析', count: 210 },
  { name: '去中心化计算', count: 178 },
]

const financial = [
  { name: '借贷', count: 3 },
  { name: '流动性挖矿', count: 8 },
  { name: '收益聚合器', count: 4 },
  { name: '稳定币', count: 6 },
  { name: '去中心化交易所 (DEX)', count: 10 },
  { name: '衍生品', count: 7 },
  { name: '资产管理', count: 5 },
  { name: '保险', count: 3 },
  { name: '预言机', count: 4 },
  { name: '跨链桥', count: 6 },
  { name: '支付', count: 7 },
  { name: '托管服务', count: 2 },
  { name: '合成资产', count: 4 },
  { name: '预测市场', count: 3 },
  { name: '去中心化身份 (DID)', count: 5 },
  { name: '代币化', count: 6 },
  { name: '众筹', count: 4 },
  { name: '流式支付', count: 3 },
  { name: '去中心化自治组织 (DAO)', count: 7 },
  { name: '抵押贷款', count: 4 },
  { name: '风险投资', count: 3 },
  { name: '指数基金', count: 5 },
  { name: '期权交易', count: 4 },
  { name: '杠杆交易', count: 6 },
  { name: '收益耕作', count: 5 },
  { name: '闪电贷', count: 4 },
  { name: '固定收益产品', count: 3 },
  { name: '流动性提供', count: 7 },
  { name: '去中心化信用评分', count: 2 },
  { name: '加密货币钱包', count: 8 },
  { name: '链上分析', count: 5 },
  { name: '代币经济模型', count: 6 },
  { name: '去中心化法币入金', count: 3 },
]

const articles = [
  {
    title: 'Aptos 区块链的并行执行模型解析',
    date: 'Aug 28, 2024',
    description: '深入探讨 Aptos 区块链的并行执行模型及其优势',
    tags: ['Aptos', '性能优化', '并行执行'],
  },
  {
    title: 'Move 语言中的资源和能力：深度解析',
    date: 'Aug 29, 2024',
    description:
      '探讨 Move 语言独特的资源和能力概念，以及它们在智能合约开发中的应用',
    tags: ['Move', '智能合约', '开发工具'],
  },
  {
    title: 'XFi：Aptos 生态系统中的 DeFi 革新',
    date: 'Aug 30, 2024',
    description: '分析 XFi 如何在 Aptos 生态系统中推动 DeFi 创新和发展',
    tags: ['XFi', '生态', '去中心化交易所 (DEX)', '借贷'],
  },
  {
    title: 'Aptos 智能合约的安全审计最佳实践',
    date: 'Aug 31, 2024',
    description: '详细介绍 Aptos 平台上智能合约审计的关键步骤和最佳实践',
    tags: ['智能合约审计', '安全性', 'Aptos'],
  },
  {
    title: '构建在 Aptos 上的区块链游戏：机遇与挑战',
    date: 'Sep 1, 2024',
    description: '探讨在 Aptos 平台上开发区块链游戏的优势和面临的技术挑战',
    tags: ['游戏', 'Aptos', 'NFT'],
  },
  {
    title: 'Aptos 的去中心化存储解决方案',
    date: 'Sep 2, 2024',
    description: '评估 Aptos 生态系统中的去中心化存储方案及其在 DApp 中的应用',
    tags: ['去中心化存储', 'Aptos', 'P2P 网络'],
  },
  {
    title: '区块链监管与 Aptos 的合规策略',
    date: 'Sep 3, 2024',
    description: '分析全球区块链监管趋势及 Aptos 的合规应对策略',
    tags: ['区块链监管与合规', 'Aptos', '去中心化身份 (DID)'],
  },
  {
    title: 'Aptos 区块链数据的可视化技术',
    date: 'Sep 4, 2024',
    description: '介绍用于可视化 Aptos 区块链数据的先进工具和技术',
    tags: ['可视化', 'Aptos', '区块链数据分析'],
  },
  {
    title: 'Aptos 的跨链互操作性解决方案',
    date: 'Sep 5, 2024',
    description: '深入探讨 Aptos 实现跨链资产转移和通信的技术方案',
    tags: ['跨链互操作', 'Aptos', '跨链协议'],
  },
  {
    title: 'Move 语言中的代币标准与经济模型设计',
    date: 'Sep 6, 2024',
    description: '解析 Move 语言中的代币标准，以及如何设计有效的代币经济模型',
    tags: ['Move', '代币经济学', '智能合约语言'],
  },
  {
    title: 'Aptos 生态系统中的 NFT 市场创新',
    date: 'Sep 7, 2024',
    description: '探索 Aptos 平台上 NFT 项目的最新发展和创新应用',
    tags: ['NFT', 'Aptos', '代币化'],
  },
  {
    title: 'Aptos 的去中心化身份解决方案',
    date: 'Sep 8, 2024',
    description: '分析 Aptos 平台上的去中心化身份项目及其在现实世界的应用',
    tags: ['去中心化身份 (DID)', 'Aptos', '区块链身份验证'],
  },
  {
    title: 'Aptos 在元宇宙建设中的角色',
    date: 'Sep 9, 2024',
    description: '讨论 Aptos 区块链如何支持和促进元宇宙生态系统的发展',
    tags: ['元宇宙', 'Aptos', '社交网络'],
  },
  {
    title: 'Aptos 的数据隐私保护机制',
    date: 'Sep 10, 2024',
    description: '深入了解 Aptos 区块链中的数据隐私保护技术和实现方法',
    tags: ['数据隐私', 'Aptos', '零知识证明'],
  },
  {
    title: 'Aptos 生态系统中的去中心化治理实践',
    date: 'Sep 11, 2024',
    description: '分析 Aptos 项目中的去中心化治理模式及其效果',
    tags: ['去中心化治理', 'Aptos', '去中心化自治组织 (DAO)'],
  },
  {
    title: 'Move 语言教育：构建下一代区块链开发者',
    date: 'Sep 12, 2024',
    description: '探讨如何有效地教授 Move 语言，培养新一代区块链开发人才',
    tags: ['区块链教育', 'Move', '开发工具'],
  },
  {
    title: 'Aptos 的可持续发展策略',
    date: 'Sep 13, 2024',
    description: '评估 Aptos 在环境友好性和长期可持续发展方面的努力',
    tags: ['可持续发展', 'Aptos', '区块链能源'],
  },
  {
    title: 'Aptos 平台上的加密艺术革命',
    date: 'Sep 14, 2024',
    description: '探索 Aptos 生态系统中新兴的加密艺术项目和创新',
    tags: ['加密艺术', 'Aptos', 'NFT'],
  },
  {
    title: 'Aptos 在医疗健康领域的应用',
    date: 'Sep 15, 2024',
    description: '分析 Aptos 区块链技术在医疗数据管理和健康记录中的潜在应用',
    tags: ['区块链医疗', 'Aptos', '数据隐私'],
  },
  {
    title: 'Aptos 驱动的供应链解决方案',
    date: 'Sep 16, 2024',
    description: '探讨 Aptos 如何改善供应链管理的透明度和效率',
    tags: ['供应链', 'Aptos', '去中心化存储'],
  },
  {
    title: 'Move 语言实现的去中心化科学平台',
    date: 'Sep 17, 2024',
    description: '介绍使用 Move 语言构建的去中心化科学(DeSci)平台及其影响',
    tags: ['去中心化科学 (DeSci)', 'Move', '智能合约'],
  },
  {
    title: 'Aptos 生态系统中的旅游业创新',
    date: 'Sep 18, 2024',
    description: '探索 Aptos 区块链如何革新旅游行业的运营和用户体验',
    tags: ['区块链旅游', 'Aptos', '去中心化身份 (DID)'],
  },
  {
    title: 'Aptos 支持的区块链慈善项目',
    date: 'Sep 19, 2024',
    description: '分析 Aptos 平台上的慈善项目如何提高透明度和效率',
    tags: ['区块链慈善', 'Aptos', '智能合约'],
  },
  {
    title: 'Move 语言在去中心化工作平台中的应用',
    date: 'Sep 20, 2024',
    description: '讨论使用 Move 语言构建的去中心化工作和自由职业平台',
    tags: ['去中心化工作', 'Move', '智能合约'],
  },
  {
    title: 'Aptos 生态系统中的质押和挖矿策略',
    date: 'Sep 21, 2024',
    description: '比较 Aptos 网络中不同的质押和挖矿方法及其收益',
    tags: ['加密货币采矿', 'Aptos', '流动性挖矿'],
  },
  {
    title: 'Aptos 驱动的绿色能源解决方案',
    date: 'Sep 22, 2024',
    description: '探讨 Aptos 区块链在推动绿色能源采用和管理中的作用',
    tags: ['区块链能源', 'Aptos', '可持续发展'],
  },
  {
    title: 'Move 语言在房地产通证化中的应用',
    date: 'Sep 23, 2024',
    description: '分析使用 Move 语言实现房地产通证化的技术细节和优势',
    tags: ['区块链房地产', 'Move', '代币化'],
  },
  {
    title: 'Aptos 的 Layer 2 扩展解决方案',
    date: 'Sep 24, 2024',
    description: '深入探讨 Aptos 的 Layer 2 扩容技术及其对网络性能的影响',
    tags: ['L2 扩容', 'Aptos', '性能优化'],
  },
  {
    title: 'Move 语言中的形式化验证技术',
    date: 'Sep 25, 2024',
    description: '介绍 Move 语言中使用形式化验证技术确保智能合约安全性的方法',
    tags: ['智能合约形式化验证', 'Move', '安全性'],
  },
  {
    title: 'Aptos 的跨链桥接技术解析',
    date: 'Sep 26, 2024',
    description: '详细分析 Aptos 与其他区块链之间的跨链桥接实现原理',
    tags: ['跨链桥', 'Aptos', '跨链协议'],
  },
  {
    title: 'Aptos 区块链的共识机制深度解析',
    date: 'Sep 27, 2024',
    description:
      '详细探讨 Aptos 区块链采用的共识机制及其在网络安全和效率方面的优势',
    tags: ['Aptos', '共识机制', '区块链网络安全'],
  },
  {
    title: 'Move 语言中的密码学原语应用',
    date: 'Sep 28, 2024',
    description: '探索 Move 语言中可用的密码学函数及其在智能合约中的实际应用',
    tags: ['Move', '密码学', '智能合约'],
  },
  {
    title: 'Aptos 生态系统中的稳定币项目分析',
    date: 'Sep 29, 2024',
    description: '对比分析 Aptos 平台上的各种稳定币项目，评估其机制和风险',
    tags: ['Aptos', '稳定币', '金融'],
  },
  {
    title: 'Aptos 智能合约的气体优化策略',
    date: 'Sep 30, 2024',
    description: '介绍在 Aptos 平台上优化智能合约以降低气体成本的技术和方法',
    tags: ['Aptos', '智能合约', '性能优化'],
  },
  {
    title: 'Move 语言在去中心化身份验证中的应用',
    date: 'Oct 1, 2024',
    description: '探讨如何利用 Move 语言构建强大的去中心化身份验证系统',
    tags: ['Move', '去中心化身份 (DID)', '区块链身份验证'],
  },
  {
    title: 'Aptos 区块链的分片技术研究',
    date: 'Oct 2, 2024',
    description: '深入分析 Aptos 在提高可扩展性方面的分片技术研究和实现',
    tags: ['Aptos', '分片技术', '性能优化'],
  },
  {
    title: 'Aptos 生态系统中的流动性挖矿策略',
    date: 'Oct 3, 2024',
    description: '比较 Aptos 平台上不同 DeFi 项目的流动性挖矿机制和收益率',
    tags: ['Aptos', '流动性挖矿', 'DeFi'],
  },
  {
    title: 'Move 语言中的状态通道实现',
    date: 'Oct 4, 2024',
    description: '探讨如何在 Move 语言中实现状态通道以提高交易效率和降低成本',
    tags: ['Move', '状态通道', '性能优化'],
  },
  {
    title: 'Aptos 区块链在供应链金融中的应用',
    date: 'Oct 5, 2024',
    description: '分析 Aptos 如何革新供应链金融，提高透明度和效率',
    tags: ['Aptos', '供应链', '金融'],
  },
  {
    title: 'Move 语言的形式化验证工具链',
    date: 'Oct 6, 2024',
    description:
      '介绍针对 Move 语言的形式化验证工具链及其在提高合约安全性方面的作用',
    tags: ['Move', '智能合约形式化验证', '安全性'],
  },
  {
    title: 'Aptos 生态系统中的去中心化保险方案',
    date: 'Oct 7, 2024',
    description: '探索 Aptos 平台上的去中心化保险项目及其创新机制',
    tags: ['Aptos', '保险', 'DeFi'],
  },
  {
    title: 'Move 虚拟机的性能优化技术',
    date: 'Oct 8, 2024',
    description:
      '深入分析 Move 虚拟机的性能优化技术及其对智能合约执行效率的影响',
    tags: ['Move', '区块链虚拟机', '性能优化'],
  },
  {
    title: 'Aptos 区块链的数据压缩技术',
    date: 'Oct 9, 2024',
    description: '研究 Aptos 在区块链数据压缩方面的创新，及其对网络性能的提升',
    tags: ['Aptos', '区块链数据压缩', '性能优化'],
  },
  {
    title: 'Move 语言在去中心化预言机中的应用',
    date: 'Oct 10, 2024',
    description: '探讨如何使用 Move 语言构建可靠和高效的去中心化预言机系统',
    tags: ['Move', '预言机', 'DeFi'],
  },
  {
    title: 'Aptos 的跨链资产转移协议',
    date: 'Oct 11, 2024',
    description:
      '详细分析 Aptos 的跨链资产转移协议及其在促进跨链互操作性方面的作用',
    tags: ['Aptos', '跨链协议', '资产管理'],
  },
  {
    title: 'Aptos 区块链的 P2P 网络优化',
    date: 'Oct 12, 2024',
    description: '探讨 Aptos 在 P2P 网络层面的优化策略，提高网络效率和稳定性',
    tags: ['Aptos', 'P2P 网络', '性能优化'],
  },
  {
    title: 'Move 语言在 NFT 市场中的创新应用',
    date: 'Oct 13, 2024',
    description:
      '分析 Move 语言如何推动 NFT 市场的创新，包括新的标准和交易模式',
    tags: ['Move', 'NFT', '智能合约'],
  },
  {
    title: 'Aptos 生态系统中的去中心化借贷平台比较',
    date: 'Oct 14, 2024',
    description: '对比 Aptos 上主要的去中心化借贷平台，分析其风险和收益特征',
    tags: ['Aptos', '借贷', 'DeFi'],
  },
  {
    title: 'Move 语言中的资源隔离技术',
    date: 'Oct 15, 2024',
    description:
      '深入探讨 Move 语言的资源隔离机制，及其在提高智能合约安全性方面的作用',
    tags: ['Move', '安全性', '智能合约'],
  },
  {
    title: 'Aptos 区块链的轻客户端实现',
    date: 'Oct 16, 2024',
    description:
      '分析 Aptos 轻客户端的技术实现，及其在提高用户友好性方面的优势',
    tags: ['Aptos', '轻客户端技术', '区块链网络安全'],
  },
  {
    title: 'Move 语言在去中心化交易所 (DEX) 中的应用',
    date: 'Oct 17, 2024',
    description: '探讨如何使用 Move 语言构建高效和安全的去中心化交易所',
    tags: ['Move', '去中心化交易所 (DEX)', 'DeFi'],
  },
  {
    title: 'Aptos 区块链的隐私计算技术',
    date: 'Oct 18, 2024',
    description: '研究 Aptos 在区块链隐私计算方面的创新，包括零知识证明的应用',
    tags: ['Aptos', '区块链隐私计算', '零知识证明'],
  },
  {
    title: 'Move 语言中的智能合约可升级性设计',
    date: 'Oct 19, 2024',
    description: '讨论 Move 语言中实现智能合约可升级性的不同策略及其利弊',
    tags: ['Move', '智能合约', '开发工具'],
  },
  {
    title: 'Aptos 生态系统中的收益聚合器分析',
    date: 'Oct 20, 2024',
    description: '评估 Aptos 平台上主要的收益聚合器项目，比较其策略和风险',
    tags: ['Aptos', '收益聚合器', 'DeFi'],
  },
  {
    title: 'Move 语言在去中心化身份 (DID) 中的实现',
    date: 'Oct 21, 2024',
    description: '探索如何利用 Move 语言的特性构建强大的去中心化身份系统',
    tags: ['Move', '去中心化身份 (DID)', '区块链身份验证'],
  },
  {
    title: 'Aptos 区块链的分布式随机数生成机制',
    date: 'Oct 22, 2024',
    description: '分析 Aptos 如何实现安全和公平的链上随机数生成',
    tags: ['Aptos', '分布式随机数生成', '区块链网络安全'],
  },
  {
    title: 'Move 语言在衍生品交易中的应用',
    date: 'Oct 23, 2024',
    description: '探讨如何使用 Move 语言构建复杂的去中心化衍生品交易平台',
    tags: ['Move', '衍生品', 'DeFi'],
  },
  {
    title: 'Aptos 区块链的时间戳机制及其应用',
    date: 'Oct 24, 2024',
    description: '研究 Aptos 的区块链时间戳机制及其在智能合约中的重要性',
    tags: ['Aptos', '区块链时间戳', '智能合约'],
  },
  {
    title: 'Move 语言中的代码覆盖率工具分析',
    date: 'Oct 25, 2024',
    description:
      '评估针对 Move 语言的代码覆盖率工具，探讨其在提高合约质量方面的作用',
    tags: ['Move', '开发工具', '智能合约'],
  },
  {
    title: 'Aptos 生态系统中的去中心化身份验证方案',
    date: 'Oct 26, 2024',
    description: '比较 Aptos 平台上不同的去中心化身份验证方案及其应用场景',
    tags: ['Aptos', '区块链身份验证', '去中心化身份 (DID)'],
  },
]

export const AptosDoc = () => {
  return (
    <CMS
      general={general}
      technology={technology}
      financial={financial}
      articles={articles}
    />
  )
}
