import { Item } from '@/components/database/Database'

export const DOCSBASE: Item[] = [
  {
    id: 1,
    name: 'Move 语言安全性',
    status: '已实现',
    priority: '高',
    dueDate: '2023-01-01',
    assignee: 'Aptos 团队',
    progress: 100,
    relatedTo: [2, 3],
    description:
      'Move 语言的设计注重安全性，通过静态类型系统和形式化验证来防止常见的智能合约漏洞。',
    url: 'https://forum.aptosfoundation.org/',
  },
  {
    id: 2,
    name: 'Aptos 并行执行引擎',
    status: '持续优化',
    priority: '高',
    dueDate: '2023-12-31',
    assignee: '核心开发团队',
    progress: 85,
    relatedTo: [1, 5],
    description:
      'Aptos 的并行执行引擎 Block-STM 允许多个交易同时执行，显著提高了网络的吞吐量。',
    url: 'https://aptos.dev/en',
  },
  {
    id: 3,
    name: 'Move 模块系统',
    status: '已实现',
    priority: '中',
    dueDate: '2023-03-15',
    assignee: '语言设计团队',
    progress: 100,
    relatedTo: [1, 4],
    description:
      'Move 的模块系统允许开发者创建可重用的代码库，促进了智能合约的模块化开发。',
    url: 'https://learn.aptoslabs.com/en',
  },
  {
    id: 4,
    name: 'Aptos 代币标准',
    status: '持续改进',
    priority: '中',
    dueDate: '2023-09-30',
    assignee: '标准化工作组',
    progress: 75,
    relatedTo: [3, 6],
    description:
      'Aptos 提供了灵活的代币标准，支持各种类型的数字资产，包括 NFT 和 FT。',
    url: 'https://github.com/caoyang2002/Aptos-Docs/blob/main/AIP/aip-42.md',
  },
  {
    id: 5,
    name: 'Move Prover',
    status: '持续开发',
    priority: '高',
    dueDate: '2023-11-30',
    assignee: '验证工具团队',
    progress: 80,
    relatedTo: [1, 3],
    description:
      'Move Prover 是一个形式化验证工具，用于证明 Move 智能合约的正确性和安全性。',
    url: 'https://github.com/caoyang2002/Aptos-Docs/blob/main/AIP/aip-52.md',
  },
  {
    id: 6,
    name: 'Aptos 共识机制',
    status: '已实现',
    priority: '高',
    dueDate: '2023-02-28',
    assignee: '共识团队',
    progress: 100,
    relatedTo: [2, 8],
    description: 'Aptos 使用 BFT 共识机制，确保网络的高吞吐量和快速最终性。',
    url: 'https://github.com/caoyang2002/Aptos-Docs/blob/main/AIP/aip-26.md',
  },
  {
    id: 7,
    name: 'Move 资源模型',
    status: '已实现',
    priority: '高',
    dueDate: '2023-01-15',
    assignee: '语言设计团队',
    progress: 100,
    relatedTo: [1, 3],
    description:
      'Move 的资源模型确保数字资产只能被创建、移动和销毁，而不能被复制或意外丢失。',
    url: 'https://github.com/caoyang2002/Aptos-Docs/blob/main/AIP/aip-22.md',
  },
  {
    id: 8,
    name: 'Aptos 账户抽象',
    status: '规划中',
    priority: '中',
    dueDate: '2024-06-30',
    assignee: '研究团队',
    progress: 30,
    relatedTo: [4, 9],
    description:
      'Aptos 正在探索账户抽象技术，以提供更灵活和用户友好的账户管理方式。',
    url: 'https://github.com/caoyang2002/Aptos-Docs/blob/main/AIP/aip-25.md',
  },
  {
    id: 9,
    name: 'Move 标准库',
    status: '持续扩展',
    priority: '中',
    dueDate: '2023-12-31',
    assignee: '开发者关系团队',
    progress: 70,
    relatedTo: [3, 7],
    description:
      'Move 标准库提供了一系列预定义的模块和函数，简化了智能合约的开发过程。',
    url: 'https://github.com/caoyang2002/Aptos-Docs/blob/main/AIP/aip-65.md',
  },
  {
    id: 10,
    name: 'Aptos 跨链桥接',
    status: '开发中',
    priority: '高',
    dueDate: '2024-03-31',
    assignee: '跨链团队',
    progress: 50,
    relatedTo: [6, 8],
    description:
      'Aptos 正在开发跨链桥接解决方案，以实现与其他区块链网络的互操作性。',
    url: 'https://github.com/caoyang2002/Aptos-Docs/blob/main/AIP/aip-70.md',
  },
]
